fn main() {
    panic!("An unrecoverable error has occurred");
}
